version: '3.8'

services:
  # Frontend Next.js application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: pptxtransed-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_AUDIT_SERVICE_URL=${AUDIT_SERVICE_URL:-http://audit-service:4006}
      - NEXT_PUBLIC_PPTX_PROCESSOR_URL=${PPTX_PROCESSOR_URL:-http://pptx-processor:8000}
      - NEXT_PUBLIC_SHARE_SERVICE_URL=${SHARE_SERVICE_URL:-http://share-service:3001}
    depends_on:
      audit-service:
        condition: service_healthy
      pptx-processor:
        condition: service_healthy
      share-service:
        condition: service_started
    networks:
      - pptxtransed-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Audit Service (Go)
  audit-service:
    build:
      context: ./services/audit-service
      dockerfile: Dockerfile
      args:
        - GO_ENV=production
    container_name: pptxtransed-audit-service
    ports:
      - "4006:4006"
    environment:
      - PORT=4006
      - LOG_LEVEL=info
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN:-https://yourdomain.com}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      - HTTP_TIMEOUT=30s
      - HTTP_MAX_IDLE_CONNS=100
      - HTTP_MAX_CONNS_PER_HOST=10
      - HTTP_IDLE_CONN_TIMEOUT=90s
      - CACHE_JWT_TTL=5m
      - CACHE_SHARE_TOKEN_TTL=1m
      - CACHE_CLEANUP_INTERVAL=10m
      - MAX_PAGE_SIZE=100
      - DEFAULT_PAGE_SIZE=50
    networks:
      - pptxtransed-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:4006/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PPTX Processor Service (Python)
  pptx-processor:
    build:
      context: ./services/pptx-processor
      dockerfile: Dockerfile
    container_name: pptxtransed-pptx-processor
    ports:
      - "8000:8000"
    environment:
      # API Configuration
      - API_ENV=production
      - API_PORT=8000
      - API_HOST=0.0.0.0
      - LOG_LEVEL=info
      # LibreOffice Configuration
      - LIBREOFFICE_PATH=/usr/bin/soffice
      # Processing Configuration
      - TEMP_UPLOAD_DIR=/tmp/uploads
      - TEMP_PROCESSING_DIR=/tmp/processing
      # Supabase Configuration
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_ANON_KEY}
      # CORS Configuration
      - CORS_ORIGIN=${CORS_ORIGIN:-https://yourdomain.com}
    volumes:
      - pptx_uploads:/tmp/uploads
      - pptx_processing:/tmp/processing
    networks:
      - pptxtransed-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Share Service (Bun)
  share-service:
    build:
      context: ./services/share-service
      dockerfile: Dockerfile
    container_name: pptxtransed-share-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=production
      - CORS_ORIGIN=${CORS_ORIGIN:-https://yourdomain.com}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    networks:
      - pptxtransed-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  pptxtransed-network:
    driver: bridge

volumes:
  pptx_uploads:
    name: pptxtransed_pptx_uploads
  pptx_processing:
    name: pptxtransed_pptx_processing 