# Docker Compose override for using .env files in services
# Usage: docker-compose -f docker-compose.yml -f docker-compose.env.yml up
# 
# This override file configures services to use their individual .env files
# instead of passing environment variables from docker-compose.yml
# 
# Prerequisites:
# 1. Run `node scripts/docker-manager.js env` to create all .env files
# 2. Ensure each service directory has a .env file

services:
  # Audit Service - uses services/audit-service/.env
  audit-service:
    env_file:
      - ./services/audit-service/.env
    # Remove specific environment variables since they'll come from .env file
    environment: []

  # PPTX Processor Service - uses services/pptx-processor/.env  
  pptx-processor:
    env_file:
      - ./services/pptx-processor/.env
    # Keep only Docker-specific overrides
    environment:
      - API_HOST=0.0.0.0
      - TEMP_UPLOAD_DIR=/tmp/uploads
      - TEMP_PROCESSING_DIR=/tmp/processing

  # Share Service - uses services/share-service/.env
  share-service:
    env_file:
      - ./services/share-service/.env
    environment: []

  # Translation Session Service - uses services/translation-session-service/.env
  translation-session-service:
    env_file:
      - ./services/translation-session-service/.env
    environment: [] 