basePath: /api/v1
definitions:
  domain.APIError:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  domain.AuditAction:
    enum:
    - create
    - edit
    - merge
    - reorder
    - comment
    - export
    - share
    - unshare
    - view
    type: string
    x-enum-varnames:
    - ActionCreate
    - ActionEdit
    - ActionMerge
    - ActionReorder
    - ActionComment
    - ActionExport
    - ActionShare
    - ActionUnshare
    - ActionView
  domain.AuditEntry:
    properties:
      details:
        type: object
      id:
        example: 550e8400-e29b-41d4-a716-446655440000
        type: string
      ipAddress:
        example: 192.168.1.1
        type: string
      sessionId:
        example: 550e8400-e29b-41d4-a716-446655440001
        type: string
      timestamp:
        example: "2023-12-01T10:30:00Z"
        type: string
      type:
        example: edit
        type: string
      userAgent:
        example: Mozilla/5.0
        type: string
      userId:
        example: 550e8400-e29b-41d4-a716-446655440002
        type: string
    type: object
  domain.AuditResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/domain.AuditEntry'
        type: array
      totalCount:
        example: 42
        type: integer
    type: object
  handlers.CreateEventRequest:
    properties:
      details: {}
      sessionId:
        type: string
      timestamp:
        type: string
      type:
        $ref: '#/definitions/domain.AuditAction'
    required:
    - sessionId
    - type
    type: object
  handlers.CreateEventResponse:
    properties:
      id:
        type: string
      sessionId:
        type: string
      success:
        type: boolean
      timestamp:
        type: string
      type:
        $ref: '#/definitions/domain.AuditAction'
      userId:
        type: string
    type: object
host: localhost:4006
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: A read-only microservice for accessing PowerPoint translation session
    audit logs
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Audit Service API
  version: 1.0.0
paths:
  /events:
    post:
      consumes:
      - application/json
      description: Creates a new audit event for a session
      parameters:
      - description: Event details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateEventRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.CreateEventResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.APIError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/domain.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.APIError'
      security:
      - BearerAuth: []
      summary: Create a new audit event
      tags:
      - Audit
  /sessions/{sessionId}/history:
    get:
      consumes:
      - application/json
      description: Retrieves paginated audit log entries for a specific session
      parameters:
      - description: Session ID
        in: path
        name: sessionId
        required: true
        type: string
      - description: 'Number of items to return (default: 50, max: 100)'
        in: query
        name: limit
        type: integer
      - description: 'Number of items to skip (default: 0)'
        in: query
        name: offset
        type: integer
      - description: Share token for reviewer access
        in: query
        name: share_token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.AuditResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.APIError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/domain.APIError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/domain.APIError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/domain.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.APIError'
      security:
      - BearerAuth: []
      summary: Get audit history for a session
      tags:
      - Audit
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
