openapi: 3.1.0
info:
  title: PPTX Processor Microservice API
  description: >
    API for converting PowerPoint (PPTX) presentations to SVGs and extracting text data with positioning information.
    This service is a critical component of the PowerPoint Translator App, enabling high-fidelity slide rendering
    and text translation while maintaining visual fidelity.
  version: 1.0.0
  contact:
    name: PowerPoint Translator App Team
servers:
  - url: https://api.pptx-processor.example.com/v1
    description: Production server
  - url: https://staging.pptx-processor.example.com/v1
    description: Staging server
  - url: http://localhost:8000/v1
    description: Local development server

tags:
  - name: processing
    description: PPTX processing operations
  - name: status
    description: Processing status operations
  - name: health
    description: Service health operations

paths:
  /process:
    post:
      tags:
        - processing
      summary: Process a PPTX file
      description: Upload a PPTX file for processing, converting slides to SVGs and extracting text data
      operationId: processPptx
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
                - sessionId
                - supabaseUrl
                - supabaseKey
              properties:
                file:
                  type: string
                  format: binary
                  description: The PPTX file to process
                sessionId:
                  type: string
                  description: Unique identifier for the translation session
                supabaseUrl:
                  type: string
                  description: The Supabase project URL for storing assets
                supabaseKey:
                  type: string
                  description: The Supabase API key for authorization
                sourceLanguage:
                  type: string
                  description: The source language of the presentation
                targetLanguage:
                  type: string
                  description: The target language for translation
                generateThumbnails:
                  type: boolean
                  description: Whether to generate slide thumbnails
                  default: true
      responses:
        '202':
          description: Processing started successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessingResponse'
        '400':
          description: Bad request - invalid file or parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - invalid Supabase credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /process/batch:
    post:
      tags:
        - processing
      summary: Process multiple PPTX files
      description: Upload multiple PPTX files for batch processing
      operationId: processBatchPptx
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - files
                - batchId
                - supabaseUrl
                - supabaseKey
              properties:
                files:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: The PPTX files to process
                batchId:
                  type: string
                  description: Unique identifier for the batch
                sessionIds:
                  type: array
                  items:
                    type: string
                  description: Unique identifiers for each translation session
                supabaseUrl:
                  type: string
                  description: The Supabase project URL for storing assets
                supabaseKey:
                  type: string
                  description: The Supabase API key for authorization
      responses:
        '202':
          description: Batch processing started successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchProcessingResponse'
        '400':
          description: Bad request - invalid files or parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - invalid Supabase credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /status/{jobId}:
    get:
      tags:
        - status
      summary: Get processing status
      description: Check the status of a processing job
      operationId: getProcessingStatus
      parameters:
        - name: jobId
          in: path
          description: ID of the processing job
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Processing status retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessingStatus'
        '404':
          description: Job not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /results/{sessionId}:
    get:
      tags:
        - status
      summary: Get processing results
      description: Retrieve the results of a completed processing job
      operationId: getProcessingResults
      parameters:
        - name: sessionId
          in: path
          description: ID of the translation session
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Results retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessedPresentation'
        '404':
          description: Results not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /health:
    get:
      tags:
        - health
      summary: Check service health
      description: Get the health status of the service
      operationId: getHealthStatus
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'
        '500':
          description: Service is unhealthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    ProcessingResponse:
      type: object
      required:
        - jobId
        - sessionId
        - status
        - message
      properties:
        jobId:
          type: string
          description: Unique identifier for the processing job
        sessionId:
          type: string
          description: Unique identifier for the translation session
        status:
          type: string
          enum: [queued, processing]
          description: Current status of the processing job
        message:
          type: string
          description: Informational message
        estimatedCompletionTime:
          type: string
          format: date-time
          description: Estimated time of completion

    BatchProcessingResponse:
      type: object
      required:
        - batchId
        - jobs
      properties:
        batchId:
          type: string
          description: Unique identifier for the batch
        jobs:
          type: array
          items:
            type: object
            properties:
              jobId:
                type: string
                description: Unique identifier for the processing job
              sessionId:
                type: string
                description: Unique identifier for the translation session
              status:
                type: string
                enum: [queued, processing]
                description: Current status of the processing job

    ProcessingStatus:
      type: object
      required:
        - jobId
        - sessionId
        - status
        - progress
      properties:
        jobId:
          type: string
          description: Unique identifier for the processing job
        sessionId:
          type: string
          description: Unique identifier for the translation session
        status:
          type: string
          enum: [queued, processing, completed, failed]
          description: Current status of the processing job
        progress:
          type: integer
          minimum: 0
          maximum: 100
          description: Progress percentage of the processing job
        currentStage:
          type: string
          description: Current processing stage
        message:
          type: string
          description: Informational or error message
        completedAt:
          type: string
          format: date-time
          description: Time when processing completed (if status is completed)
        error:
          type: string
          description: Error details (if status is failed)

    ProcessedPresentation:
      type: object
      required:
        - sessionId
        - slideCount
        - processingStatus
        - slides
      properties:
        sessionId:
          type: string
          description: Unique identifier for the translation session
        slideCount:
          type: integer
          description: Total number of slides in the presentation
        processingStatus:
          type: string
          enum: [completed, partially_completed, failed]
          description: Overall status of the processing
        processingTime:
          type: integer
          description: Processing time in seconds
        slides:
          type: array
          items:
            $ref: '#/components/schemas/ProcessedSlide'

    ProcessedSlide:
      type: object
      required:
        - slideId
        - slideNumber
        - svgUrl
        - originalWidth
        - originalHeight
        - shapes
      properties:
        slideId:
          type: string
          description: Unique identifier for the slide
        slideNumber:
          type: integer
          description: Slide number in the presentation (1-based)
        svgUrl:
          type: string
          description: URL to the SVG representation of the slide
        originalWidth:
          type: integer
          description: Original width of the slide in pixels
        originalHeight:
          type: integer
          description: Original height of the slide in pixels
        thumbnailUrl:
          type: string
          description: URL to a thumbnail image of the slide
        shapes:
          type: array
          items:
            $ref: '#/components/schemas/SlideShape'

    SlideShape:
      type: object
      required:
        - shapeId
        - shapeType
        - originalText
        - xCoordinate
        - yCoordinate
        - width
        - height
        - coordinatesUnit
      properties:
        shapeId:
          type: string
          description: Unique identifier for the shape
        shapeType:
          type: string
          enum: [text, table_cell, chart_text, smartart_text]
          description: Type of the shape
        originalText:
          type: string
          description: Original text content of the shape
        xCoordinate:
          type: number
          format: float
          description: X coordinate of the shape
        yCoordinate:
          type: number
          format: float
          description: Y coordinate of the shape
        width:
          type: number
          format: float
          description: Width of the shape
        height:
          type: number
          format: float
          description: Height of the shape
        coordinatesUnit:
          type: string
          enum: [percentage, px]
          description: Unit of the coordinates (percentage of slide or pixels)
        fontSize:
          type: number
          format: float
          description: Font size of the text
        fontFamily:
          type: string
          description: Font family of the text
        fontWeight:
          type: string
          description: Font weight of the text (normal, bold)
        fontStyle:
          type: string
          description: Font style of the text (normal, italic)
        color:
          type: string
          description: Color of the text in hex format
        readingOrder:
          type: integer
          description: Reading order of the text element (1-based)
        parentId:
          type: string
          description: ID of the parent shape (for grouped elements)

    HealthStatus:
      type: object
      required:
        - status
        - version
      properties:
        status:
          type: string
          enum: [healthy, degraded, unhealthy]
          description: Overall health status of the service
        version:
          type: string
          description: Version of the service
        uptime:
          type: number
          description: Service uptime in seconds
        components:
          type: object
          additionalProperties:
            type: object
            properties:
              status:
                type: string
                enum: [healthy, degraded, unhealthy]
              message:
                type: string

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Error code
        message:
          type: string
          description: Error message
        details:
          type: object
          description: Additional error details 